### ISSUE TITLE
FunctionInfo.cpp: callsiteCnt is not calculated

### ISSUE THREAD

**Issue by chobits** [rpgzysb/OptimizingCompiler#1]
https://github.com/rpgzysb/OptimizingCompiler/blob/2b8501231a8ac36cad36636f83a8e0a0bfd9861a/scalarOpt/FunctionInfo/FunctionInfo.cpp#L38

I refer to ur source code, but not found how to calculate callsite.
Is iterating over all instruction of function to calculate this value a good way?

**Comment by rpgzysb** [comment]
Dear Xiaocheng,

Thank you for telling me this. Actually if you want to calculate the
callsite, I think LLVM provides getNumUses() method. This shows that it is
not my final version of my submission.

By the way I am curious,

Sincerely,
Skylar

**Comment by rpgzysb** [comment]
Dear Xiaocheng,

I am curious are you taking the same course in CMU?

Sincerely,
Skylar

**Comment by chobits** [comment]
> I am curious are you taking the same course in CMU?

No, I am learning the online resource of this course.

> Actually if you want to calculate the callsite, I think LLVM provides getNumUses() method. This shows that it is not my final version of my submission.

Thanks, it's helpful to me:)

**Comment by chobits** [comment]
resolved! closing it.
